secrets:
  token-file:
    file: ./token-file

services:
  agent:
    build: ./agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cloudflared:
    image: cloudflare/cloudflared
    restart: always
    secrets:
      - token-file
    command: tunnel run --token-file /run/secrets/token-file

  traefik:
    image: traefik:v3.6
    restart: always
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.forwardedheaders.insecure=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro